### ISSUE TITLE
Mysql exception

### ISSUE THREAD

**Issue by Maxopoly** [Maxopoly/CivPvP#8]
Stack trace: 

[20:19:03 ERROR]: [CivPvP] Could not execute SQL statement!                                                                                                  │···············································································
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'yep' for key 'name'                                             │···············································································
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_79]                                                               │···············································································
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_79]                                        │···············································································
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_79]                                │···············································································
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_79]                                                                     │···············································································
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-d97e08b-880a532]                                                     │···············································································
        at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[spigot.jar:git-Spigot-d97e08b-880a532]                                                           │···············································································        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039) ~[spigot.jar:git-Spigot-d97e08b-880a532]                                           │···············································································
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot.jar:git-Spigot-d97e08b-880a532]                                               │···············································································        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot.jar:git-Spigot-d97e08b-880a532]                                               │···············································································
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot.jar:git-Spigot-d97e08b-880a532]                                                    │···············································································
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot.jar:git-Spigot-d97e08b-880a532] 
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[spigot.jar:git-Spigot-d97e08b-880a532]                                          │···············································································
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[spigot.jar:git-Spigot-d97e08b-880a532]                            │···············································································
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[spigot.jar:git-Spigot-d97e08b-880a532]                              │···············································································
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[spigot.jar:git-Spigot-d97e08b-880a532]                              │···············································································
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[spigot.jar:git-Spigot-d97e08b-880a532]                              │···············································································
        at com.gimmicknetwork.civpvpinventory.Database.execute(Database.java:97) [CivPvP.jar:?]                                                              │···············································································
        at com.gimmicknetwork.civpvpinventory.KitManager.addKit(KitManager.java:184) [CivPvP.jar:?]                                                          │···············································································
        at com.gimmicknetwork.civpvpinventory.CivpvpInventory.invSave(CivpvpInventory.java:65) [CivPvP.jar:?]                                                │···············································································
        at com.gimmicknetwork.civpvpinventory.Commands.onCommand(Commands.java:51) [CivPvP.jar:?]                                                            │···············································································
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-d97e08b-880a532]                                           │···············································································
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-d97e08b-880a532]                                   │···············································································
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-d97e08b-880a532]                          │···············································································
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-d97e08b-880a532]                   │···············································································
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-d97e08b-880a532]                                │···············································································
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-d97e08b-880a532]                                 │···············································································
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-d97e08b-880a532]                                  │···············································································
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d97e08b-880a532]                                   │···············································································
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]                                                              │···············································································
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]                                                                             │···············································································        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-d97e08b-880a532]                                                 │···············································································
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-d97e08b-880a532]                                  │···············································································
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]                                  │···············································································        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]                                  │···············································································
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]

**Comment by Maxopoly** [comment]
@TealNerd

**Comment by TealNerd** [comment]
For some reason it was trying to add a kit that already existed but the kit name is unique in the db

**Comment by TealNerd** [comment]
I meant to click comment not close and comment

**Comment by Maxopoly** [comment]
Also it deleted all the kits last night and now if you create a kit and then try to load it, it just says the kit doesnt exist. No exceptions while saving/loading.
